version: "3"

services:
  cruddybeer_nginx:
    build: ./ngnix-proxy
    image: nginx-proxy
    container_name: cruddybeer_proxy
    hostname: cruddybeer_proxy
    depends_on:
      - "cruddybeer_app"
    ports:
      - "80"
    environment:
      NGINX_PORT: 80
      UWSGI_SERVER: http://cruddybeer_app:8001

  cruddybeer_app:
    build: ./cruddybeer-app/
    image: cruddybeer-app
    container_name: cruddybeer_app
    hostname: cruddybeer_app
    depends_on:
      - "cruddybeer_db"
    ports:
      - "8001"
    environment:
      GIT_BRANCH: dockerize

  cruddybeer_db:
    image: mongo
    container_name: cruddybeer_db
    hostname: cruddybeer_db
    volumes:
      - '/var/lib/mongodb/'
