FROM ubuntu

MAINTAINER Dave Hoffman

#Install requirements like pip, flask, git and flask requirements

#Pull cruddybeer from git repo

#Run Cruddybeer in a way that Ngnix will accept - uWSGI probably.